[package]
name = "xdp-program"
version = "0.1.0"
edition = "2024"

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya", branch = "main" }

[lib]
path = "src/lib.rs"

[profile.release]
panic = "abort"